---
resources:

- name: keycloak-cas
  type: git
  icon: github
  public: true
  source:
    branch: main
    password: (("github.com"/token.token))
    uri: https://github.com/RoboJackets/keycloak-cas
    username: x-access-token
  tags:
  - resources
  webhook_token: ((webhook-token))

jobs:

- name: build
  public: true
  serial: true
  plan:
  - get: keycloak-cas
    trigger: true

  - task: build-jar
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: maven
          tag: 3-amazoncorretto-11
      inputs:
      - name: keycloak-cas
      params:
        GITHUB_TOKEN: ((github-packages-token))
      run:
        path: mvn
        dir: keycloak-cas
        args:
        - clean
        - com.spotify.fmt:fmt-maven-plugin:check
        - package
        - deploy
        - --settings
        - .concourse/settings.xml
